sudo: false
language: cpp
compiler:
- clang++
- g++
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - llvm-toolchain-precise
    packages:
    - libpcap-dev
    - libncurses5-dev
    - clang-3.7
    - g++-5
    - gcc-5
script:
- make CXX="${CXX}"
notifications:
  slack:
    secure: LeQfSXp8Itn59b5oEYqClG7hbxVpbL/dircXDEhnylkbxbpY+bgHTjG1jDyG8GUqww8PNn4cWyJ9OUTl7vxSGwLO/EBP7087N7sOr7KfXkfmqZrk8R6raJ6Rn9KcDbcqDxPQt5I4H2FNbd+OHBc3ODWOSGfbIHYFmMy3O52uCiw93DEQQVMZx9yQQ7mzXsMVyRGTpK9WrM6TTNCE5POYopXXSE2ySTOCA0szrR0f8qiYs8aPHWkCrYmdNTB70aVLCpfScee6ao76DV2RyKS7M7n3X0TZVMvKlwG2QlAcuF0oMaHiE02RZQaPKSyLdDRYTaD2uRr0XU1+r0AWelR2PgEV+8v55MoPgCDZxCJtYbiXAF73MHbsO/pGf+V5ktnZfOxxu6n9+pcN/89+f9B2OQi1SneooyIsMPqogqsuEUIq1Ji1OSjUsgfZrhDuKOf+Dg6Oz2hFZYCrG+ISgMepItvBJCEzzXCzldObEJGLZVmrKjhPXjd7/YRw1m/X2d0sTsMRXg9ApBdmh6TlUo+F7Nl1GdfVYehTN9h/bZ1a7TPGb2dZ6xew5dleCSvKBz6+zTDD5K0tq25n46czxEJPHKd9zFGLZDJ55f4/VOsQ2doHIF6xFTpishA9vXMAC+iEw94demDPGv4Og20Fd46kF88WyyWzNfYDrUH/NewLQ4w=
