
sudo: false
language: cpp

compiler:
  - clang
  - g++

addons:
  apt:
    packages:
      - libpcap-dev
      - libncurses5-dev
      - clang-3.7
      - g++-5
      - gcc-5

install:
  - if [ "$CXX" = "g++" ]; then export CXXFLAGS="-std=c++11"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXXFLAGS="-std=c++11"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - make CXXFLAGS="${CXXFLAGS}" CXX="${CXX}"

script:
  - make
