sudo: false
language: cpp
compiler:
- clang++
- g++
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - llvm-toolchain-precise
    packages:
    - libpcap-dev
    - libncurses5-dev
    - clang-3.7
    - g++-5
    - gcc-5
script:
- make CXX="${CXX}"
notifications:
  slack:
    secure: hR89EP0S8r65TF2QA2nLi8JpWzjPd63exoSqticSZPRj2gKwH4OnXp2BZ6jkfFFNDIFN21XPU8gliMQqzeOVxMlD04B70NWE/zgd3EiwH+fIQBpnIxM0M+K5mkbuBiB3/s49QICJdLycb/Auvt6rf4biukT8E8OHFMEpEus2kYJqj10DjJo8QBQsrtjFhjD1O6l4iIMJYw01ScY/19wvGYd3I/RmhGrghlImDVSCHm6JhNu7PBwhtepYiZqHd0LZjE5aJWcjHQfyioyGVGmjzhvYNPJ8w6Jzrpzq21F1bleAvJO+XqChFzWhgErkb8jRjUJXN4rpyE92dbsLzVdG1Q+/ZSXIX/tiT3zbbRpWv5P7/Vu5wRVXZgeDDdnFd0cAx5yApI9NfjosH5mxr3VTmGacEH2tiN34NW7HcASz+/43Pij33mZORHCqRJ+L3qThtk1H/37vdiPHd+EBqKntrt0OXxbTu4UaqTOBsxOdn2VOsFRKt5Kq6ERJTBtBrzYND9wnRUmhvjHeh0IYHUG9UW/ndL5YdcjeOizXgndf/L/livUU+FtJAGHU71STl6e1cVk4IZ7VZs/l+5m/xCGuCQE/5aDpffwXmKFAAmG19ehc6RIg+xx15/vTf3iUzL6jF4PaScXEAtufJSQXQHE7uENQY4V2b5MYdXXfaHdT+lA=
